### ISSUE TITLE
Compatability with baraza 2.7 - Missing rendering of Default sibling element of FORM and FORMVIEW

### ISSUE THREAD

**Issue by Vernel** [OpenBaraza/openBaraza#2]
The DEFAULT sibling element of FORM and FORMVIEW no longer renders as a blank row class in html. This became useful in instances where one wanted extra space between visual elements in html.

**Comment by denniswachira** [comment]
This is correct.
Its better you advice the case then we can create a separate tag for space generation

**Comment by Vernel** [comment]
Lol, found a solution by altering the java code
