### ISSUE TITLE
Feature Request - Google charts integration in dashboard using baraza xml

### ISSUE THREAD

**Issue by Vernel** [OpenBaraza/openBaraza#5]
It would be nice to be able to display graphs and charts on the dashboard using the baraza xml language so you can get something like the following:
![google charts](https://user-images.githubusercontent.com/11748432/147874820-7d681ec7-90a3-4aca-990d-79981cce6b06.png)

**Comment by denniswachira** [comment]
We have started to work on basic dashboard graphs but for now  you can extend the .jsp and create dashboads
